name: Update Preview Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- IMPORTANT so git push works

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Install dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 \
            libxi6 libxtst6 libnss3 libxrandr2 libasound2 \
            libpangocairo-1.0-0 libatk1.0-0 libcups2 libdrm2 \
            libdbus-1-3 libxss1 libgtk-3-0

      - name: Take screenshot
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] });
            const page = await browser.newPage();
            await page.setViewport({ width: 1280, height: 720 });
            await page.goto('https://simplebooklet.com/cpanel', { waitUntil: 'networkidle0' });
            await page.screenshot({ path: 'preview.png' });
            await browser.close();
          })();
          "

      - name: Commit and push updated screenshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add preview.png
          git commit -m "Update preview.png" || echo "No changes to commit"
          git push
